
let w = g.getWidth();
let h = g.getHeight();



Graphics.prototype.setFontOpenSans = function() {
// Actual height 48 (48 - 1)
var widths = atob("ERglJSUlJSUlJSUlEQ==");
var font = atob("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfgAAAAAAAAD/AAAAAAAAAP+AAAAAAAAA/4AAAAAAAAD/gAAAAAAAAP8AAAAAAAAAfgAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAB8AAAAAAAAA/wAAAAAAAAP/AAAAAAAAH/8AAAAAAAD//gAAAAAAB//4AAAAAAAf/8AAAAAAAP/+AAAAAAAH//gAAAAAAB//wAAAAAAA//4AAAAAAAf/+AAAAAAAH//AAAAAAAD//gAAAAAAB//wAAAAAAA//8AAAAAAAD/+AAAAAAAAP/AAAAAAAAA/wAAAAAAAAD4AAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB///AAAAAAB////wAAAAAf////4AAAAH/////wAAAA//////wAAAH//wP//gAAA/8AAAP/AAAH+AAAAH+AAAfgAAAAH4AAD8AAAAAPwAAPgAAAAAfAAA+AAAAAB8AAH4AAAAAH4AAfAAAAAAPgAB8AAAAAA+AAHwAAAAAD4AAfAAAAAAPgAB+AAAAAB+AAD4AAAAAHwAAPgAAAAAfAAA/AAAAAD8AAB+AAAAAfgAAH+AAAAH+AAAP/AAAD/wAAAf/+A//+AAAA//////wAAAB/////+AAAAB/////gAAAAA////4AAAAAAf//4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgAAAAAAAAAPAAAAAAAAAB+AAAAAAAAAPwAAAAAAAAB/AAAAAAAAAH4AAAAAAAAA/AAAAAAAAAH4AAAAAAAAA/AAAAAAAAAH4AAAAAAAAAfAAAAAAAAAD///////wAAP///////AAA///////8AAD///////wAAP///////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8AAAMAAAAAPwAAB4AAAAB/AAAHwAAAAP8AAA/AAAAB/wAAH4AAAAP/AAAfAAAAB/8AAB8AAAAP/wAAPgAAAB/fAAA+AAAAP58AAD4AAAB/HwAAfgAAAP4fAAB8AAAB/B8AAHwAAAP4HwAAfAAAB/AfAAB8AAAP4B8AAHwAAB/AHwAAfgAAf4AfAAA+AAD/AB8AAD4AAf4AHwAAPwAH/AAfAAAfgB/wAB8AAB/w/+AAHwAAD///wAAfAAAH//+AAB8AAAP//gAAHwAAAf/4AAAfAAAAf+AAAB8AAAAAAAAAHwAAAAAAAAAfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAfAAABwAAAAB+AAAHwAAAAD4AAA/AAAAAPwAAH4AAAAAfAAAfAAAAAB8AAB8AAAAAHwAAPwAD4AAfAAA+AAPgAB+AAD4AA+AAD4AAPgAD4AAPgAB8AAPgAA+AAHwAA+AAD4AAfAAD4AAPgAB8AAPgAA+AAHwAB+AAD4AAfAAH4AAfAAB+AAfgAB8AAD4AD/AAHwAAPgAP8AAfAAA/AB/wAD8AAD+APvgAfgAAH+H+fAD+AAAf//x+AfwAAA///H///AAAB//4P//4AAAD//Af//AAAAD/wA//4AAAAB4AB//AAAAAAAAB/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/AAAAAAAAAP8AAAAAAAAB/wAAAAAAAAP/AAAAAAAAD/8AAAAAAAAf/wAAAAAAAH+fAAAAAAAA/x8AAAAAAAP8HwAAAAAAB/gfAAAAAAAf8B8AAAAAAD/AHwAAAAAAf4AfAAAAAAH+AB8AAAAAA/wAHwAAAAAP8AAfAAAAAB/gAB8AAAAAf4AAHwAAAAD/AAAfAAAAAf4AAB8AAAAH+AAAHwAAAA/gAAAfAAAAD///////wAAP///////AAA///////8AAD///////wAAP///////AAAAAAAAfAAAAAAAAAB8AAAAAAAAAHwAAAAAAAAAfAAAAAAAAAB8AAAAAAAAAHwAAAAAAAAAfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHwAAAAAAAAAfgAAAB//AAA+AAA///+AAD8AAD///4AAHwAAP///gAAfAAA///+AAB8AAD/+D4AAHwAAPgAPgAAfgAA+AA+AAA+AAD4AD4AAD4AAPgAPgAAPgAA+AA+AAA+AAD4AD4AAD4AAPgAPgAAPgAA+AA+AAA+AAD4AD4AAHwAAPgAPgAAfAAA+AA/AAB8AAD4AD8AAPwAAPgAH4AA+AAA+AAfgAH4AAD4AA/gB/AAAPgAD/gf8AAA+AAH///gAAD4AAP//8AAAAAAAf//gAAAAAAA//8AAAAAAAA//AAAAAAAAAfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH4AAAAAAAA///gAAAAAA////wAAAAAP////wAAAAD/////gAAAA//////AAAAH/+Pwf+AAAA/8B8AP8AAAH+APgAP4AAAfwB8AAfgAAD8APgAA/AAAfgA8AAB8AAB+AHwAAHwAAHwAfAAAfgAA+AB4AAA+AAD4AHgAAD4AAPgAeAAAPgAA8AB4AAA+AAHwAHwAAD4AAfAAfAAAfAAB8AB8AAB8AAHwAH4AAPwAAfAAPwAB+AAB8AA/gAP4AAHwAB/gD/AAAPAAH///8AAA+AAP///gAAAAAAf//4AAAAAAAf//AAAAAAAAf/wAAAAAAAAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwAAAAAAAAAPgAAAAAAAAA+AAAAAAAAAD4AAAAAAAAAPgAAAAAAAAA+AAAAAAAAAD4AAAAAAAAAPgAAAAADAAA+AAAAAB8AAD4AAAAAfwAAPgAAAAH/AAA+AAAAB/8AAD4AAAAf/wAAPgAAAH/8AAA+AAAD//AAAD4AAA//wAAAPgAAP/4AAAA+AAD/+AAAAD4AA//gAAAAPgAP/4AAAAA+AH/8AAAAAD4B//AAAAAAPgf/wAAAAAA+H/8AAAAAAD5/+AAAAAAAP//gAAAAAAA//4AAAAAAAD/+AAAAAAAAP/gAAAAAAAA/wAAAAAAAAD8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/4AAAAA+AAP/4AAAAf/AB//wAAAD/+AP//gAAAf/8B///AAAD//4P+P+AAAf//x/AP4AAB/A/n4APgAAPwB//AA/AAA+AD/4AB8AAD4AH/AAHwAAPAAP8AAPAAB8AA/gAA+AAHwAB+AAD4AAfAAH4AAPgAB8AAfgAA+AAHwAB+AAD4AAfAAP8AAPgAA8AA/wAA+AAD4AH/gAHwAAPgA/+AAfAAA/AH78AD8AAB/A/H4APgAAH//8fwD+AAAP//g/4/wAAAf/8B///AAAA//gD//4AAAB/4AH//AAAAA+AAP/wAAAAAAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8AAAAAAAAD//AAAAAAAA///AAAAAAAH//+AAAAAAB///8AAfAAAH///4AA8AAA/4B/gAD4AAH8AB/AAPgAAfgAD8AA+AAD8AAH4AD4AAPgAAPgAPgAA+AAA+AA+AAH4AAD4AD4AAfAAAPgAPAAB8AAAeAB8AAHwAAB4AHwAAfAAAPgAfAAB+AAA+AD8AAD4AAD4APgAAPgAAPAB+AAA/AAB8APwAAB+AAPgB/AAAH8AA8Af4AAAP8APgP/AAAAf+B8P/4AAAA//////AAAAB/////wAAAAD////8AAAAAD////AAAAAAB///gAAAAAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+AAAfgAAAAP8AAD/AAAAB/wAAP+AAAAH/AAA/4AAAAf8AAD/gAAAA/wAAP8AAAAB+AAAfgAAAABAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==");
var scale = 1; // size multiplier for this font
g.setFontCustom(font, 46, widths, 64+(scale<<8)+(1<<16));  
};


function draw() {
  var d = new Date();
  var da = d.toString().split(" ");
  var time = da[4].substr(0,5);

  g.reset();
  g.clearRect(0, 30, w, h);
  g.setFontAlign(0, -1);
  //g.setFont("Vector", 60);
  g.setFontOpenSans();
  g.drawString(time, w/2, h/3);
}

// handle switch display on by pressing BTN1
Bangle.on('lcdPower', function(on) {
  if (on) draw();
});

g.clear();
Bangle.loadWidgets();
Bangle.drawWidgets();
setInterval(draw, 15000); // refresh every 15s
draw();
// Show launcher when button pressed
Bangle.setUI("clock");
