
Graphics.prototype.setFontMKSansTallX = function(scale) {
  // Actual height 43 (46 - 4)
  g.setFontCustom(atob("AAAAAAAAAAAAAAAAPgAAAAAAAD4AAAAAAAA+AAAAAAAAPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+AAAAAAAD/gAAAAAAH/wAAAAAAP/gAAAAAAP/AAAAAAAf/AAAAAAAf+AAAAAAA/8AAAAAAB/8AAAAAAB/4AAAAAAD/wAAAAAAH/wAAAAAAH/gAAAAAAP/gAAAAAAP/AAAAAAAD+AAAAAAAA+AAAAAAAAAAAAAAAAAAAAAAAAAAAAA///4AAAAH////+AAAH/////wAAD/////+AAB//////wAAfAAAAB8AAPgAAAAPgAD4AAAAD4AA8AAAAAeAAPAAAAAHgADwAAAAB4AA8AAAAAeAAPAAAAAHgADwAAAAB4AA8AAAAAeAAPAAAAAHgADwAAAAB4AA+AAAAA+AAPgAAAAPgAB8AAAAHwAAf/////8AAD/////+AAAf/////AAAD/////AAAAA///4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAPAAAAAAAAH4AAAAAAAD8AAAB4AAD+AAAAeAAB+AAAAHgAA/AAAAB4AA/gAAAAeAAPgAAAAHgAD//////4AA//////+AAP//////gAD//////4AA//////+AAAAAAAAHgAAAAAAAB4AAAAAAAAeAAAAAAAAHgAAAAAAAB4AAAAAAAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AB//gAAf/AB//4AAP/wA//+AAH/8AP//gAB+AAH8B4AAeAAB8AeAAPgAA+AHgAD4AAPgB4AA8AADwAeAAPAAA8AHgADwAAPAB4AA8AADwAeAAPAAA8AHgADwAAfAB4AA8AAHwAeAAPAAB8AHgAD4AAfAB4AA+AAPgAeAAPwAD4AHgAB/gP+AB4AAf///AAeAAD///gAHgAAf//wAB4AAA//gAAeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPwAB/4AAAf+AAf/gAAP/gAH/8AAH/4AA//AAB+AAAAHwAA+AAAAA+AAPgAAAAPgAD4AAAAB4AA8AAAAAeAAPAAPAAHgADwADwAB4AA8AA8AAeAAPAAPAAHgADwADwAB4AA8AA8AAeAAPAAfAAHgADwAHwAD4AA+AB+AA+AAPgA/gAPgAB+Af8APwAAf//v//8AAD//7//+AAAf/8f//AAAD/8B//gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/AAAAAAAA/wAAAAAAA/8AAAAAAAf/AAAAAAAf7wAAAAAAf48AAAAAAP4PAAAAAAP8DwAAAAAP8A8AAAAAH8APAAAAAH+ADwAAAAH+AA8AAAAD/AAPAAAAD/AADwAAAD/AAA8AAAB/gAAPAAAA/gAADwAAAPgAAA8AAAD//////4AA//////+AAP//////gAD//////4AAAAAADwAAAAAAAA8AAAAAAAAPAAAAAAAADwAAAAAAAA8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//8A/wAAD///AP/AAA///wD/4AAP//8Af/AAD//8AAHwAA8AOAAA+AAPAHgAAPgADwD4AAD4AA8A8AAAeAAPAPAAAHgADwDwAAB4AA8A8AAAeAAPAPAAAHgADwDwAAB4AA8A8AAAeAAPAPgAAHgADwD4AAD4AA8A+AAA+AAPAHwAAfAADwB/wB/wAA8AP///4AAPAB///+AADwAP//+AAAAAAf/+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///gAAAA/////wAAAf/////AAAP/////4AAH//////AAB+AHgAPwAA+ADwAA+AAPgA8AAPgAD4APAAD4AA8AHgAAeAAPAB4AAHgADwAeAAB4AA8AHgAAeAAPAB4AAHgADwAeAAB4AA8AHgAAeAAPAB4AAHgAD4AfAAD4AA+ADwAA+AAHwA8AAPAAB/gP4APwAAf8D///8AAD/Af//+AAAPwD///AAAAcAP//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AAAAAAAAPAAAAAAAADwAAAAAAAA8AAAAAAAAPAAAAABgADwAAAAB4AA8AAAAB+AAPAAAAB/gADwAAAB/4AA8AAAB/4AAPAAAD/4AADwAAD/wAAA8AAD/wAAAPAAD/wAAADwAD/wAAAA8AH/wAAAAPAH/gAAAADwH/gAAAAA8H/gAAAAAPH/gAAAAAD3/gAAAAAA//gAAAAAAP/AAAAAAAD/AAAAAAAA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHwAAAA//A//4AAA//4f//AAAf//P//4AAH//////AAD8Af8APwAA+AD8AA+AAPAAfAAPgADwAHwAD4AA8AB4AAeAAPAAeAAHgADwAHgAB4AA8AB4AAeAAPAAeAAHgADwAHgAB4AA8AB4AAeAAPAAeAAHgADwAHwAD4AA8AB8AA+AAPgA/gAPgAB+A/8APwAAf/////8AAD//z//+AAAf/4f//AAAB/4D//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4AAAAAAA//+APgAAAf//wD/AAAP//+A/4AAH///wP/AAB+AD8AfwAA+AAPAA8AAPgAD4APgAD4AA+AD4AA8AAHgAeAAPAAB4AHgADwAAeAB4AA8AAHgAeAAPAAB4AHgADwAAeAB4AA8AAHgAeAAPAAB4AHgAD4AA8AD4AA+AAPAA+AAPwADgAfgAB+ADwAfwAAf/////8AAD/////+AAAf/////AAAB/////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4AAPgAAAA+AAD4AAAAPgAA+AAAAD4AAPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="), 46, atob("CREdHh4eHh4eHh4eDw=="), 56+(scale<<8)+(1<<16));
}

Graphics.prototype.setFontMKSansTallX22 = function(scale) {
  // Actual height 22 (24 - 3)
  g.setFontCustom(atob("AAABgAAADgAAADgAAAAAAAAAAAAAHgAAA/AAAD8AAAfgAAD8AAAPwAAB+AAAH4AAAHAAAAAAAAAA//8AD///AD///gHAADgGAABgGAABgGAABgGAABgGAABgHAADgHgAHgD///AB//+AAAAAAAAAAAAAAAAAAAAAAAAAAAcAAAA8ABgBwABgHgABgHAABgH///gH///gAAABgAAABgAAABgAAAAAAAAAAAAAAAAAAfgB8D/gD8D/gHAHBgHAGBgGAGBgGAGBgGAOBgGAOBgHAOBgHAeBgD/8BgD/4BgAfABgAAAAAAAAAAAAA8AD8A/AD8A/gHAADgHAADgGAYBgGAYBgGAYBgGAYBgHA4DgHA8DgH///gD/v/AA+D8AAAAAAAABwAAAHwAAAPwAAA8wAAD4wAAHgwAAfAwAB8AwADwAwAHgAwAH///gH///gH///gAAAwAAAAwAAAAAAAAAAAAAAcAH/w/AH/wfgGBgDgGDADgGDABgGDABgGDABgGDABgGDgDgGDwDgGB//AGA/+AAAHwAAAAAAAAAAAA//8AD///AD///AHAwDgHBgDgGBgBgGBgBgGBgBgGBgBgHBgDgHBwDgDw//ABw//AAAP4AAAAAAAAAAAGAAAAGAAAAGAAAgGAADgGAAPgGAB+AGAH4AGAfgAGB+AAGH4AAG/AAAH8AAAHwAAAAAAAAAAAAAAAAAAAcH8AD/P/AH///gHB4DgGAwDgGAwBgGAwBgGAwBgGAwBgGAwDgHB4DgH///gD/P/AAYD8AAAAAAAAAAAA/gAAD/4eAH/8fAHAcDgHAMDgGAMBgGAMBgGAMBgGAMBgHAMDgHAYDgD///AD///AAf/8AAAAAAAAAAAAAAAAAAAAAADgDgADgDgAAAAAAAAAAAAAA"), 46, atob("BQkPEBAQEBAQEBAQCA=="), 30+(scale<<8)+(1<<16));
}

function setTimeFont() {
  //g.setFontMPLUSRounded1c();
  //g.setFontRockoFLFBold();
  //g.setFontUbuntuTitle();
  g.setFontMKSansTallX();
}

function setSmallFont() {
  //g.setFont('Vector',22);
  g.setFontMKSansTallX22();
}

const h = g.getHeight();
const w = g.getWidth();

function draw() {
  var d = new Date();
  var da = d.toString().split(" ");
  var time = da[4].substr(0,5);

  g.reset();
  g.clearRect(0, 24, w, h);

  // weather
  g.setColor(g.theme.fg);
  setSmallFont();
  g.setFontAlign(0, -1);
  g.drawString("* 24 C", w/2, 24);
  
  // time
  g.setColor(g.theme.fg);
  g.setFontAlign(0, 0);
  setTimeFont();
  g.drawString(time, w/2, h/2);
  //g.drawString('00:00', w/2, h/2);

  // day, dd, month
  g.setColor(g.theme.fg);
  setSmallFont();
  g.setFontAlign(0, 0);
  g.drawString('Wed, 15 Dec', w/2, 3*h/4);

  // steps
  //g.setColor(g.theme.fg);
  g.setColor('#ff0');
  setSmallFont();
  g.setFontAlign(0, -1);
  g.drawString('2546', w/2, h - 36);
}


g.clear();
Bangle.loadWidgets();
Bangle.drawWidgets();
setInterval(draw, 15000); // refresh every 15s
draw();
// Show launcher when button pressed
Bangle.setUI("clock");
