Graphics.prototype.setFontArista2 = function(scale) {
  // Actual height 42 (48 - 7)
  g.setFontCustom(atob("AAAAAAAAAAAAAAHAAAAAAAB8AAAAAAAfwAAAAAAD+AAAAAAAfwAAAAAAD+AAAAAAAPgAAAAAAAAAAAAAAACAAAAAAAD8AAAAAAH/wAAAAAH/+AAAAAH//wAAAAH//+AAAAH///gAAAH///4AAAP///4AAAH///4AAAB///4AAAAP//wAAAAB//wAAAAAP/wAAAAAA/wAAAAAADwAAAAAAAAAAAAAAAAAAfwAAAAAAP/wAAAAAH//AAAAAB//8AAAAAf//wAAAAH///AAAAB///8AAAAP+D/gAAAD/gP+AAAAf4A/wAAAD+AD+AAAAfwAfwAAAD+AD+AAAAfwAfwAAAD+AD+AAAAf4A/wAAAD/gP+AAAAP+D/gAAAB///8AAAAH///AAAAAf//wAAAAB//8AAAAAH//AAAAAAf/wAAAAAAfwAAAAAAAAAAAAAAGAAAAAAAB8AAAAAAAfwAAAAAAH+AAAAAAA/wAAAAAAP///AAAAB///8AAAAf///wAAAD///+AAAAf///wAAAD///+AAAAP///gAAAA///4AAAAAAAAAAAAAAAAAAAAAAcAHAAAAAH4B8AAAAD/AfwAAAA/4H+AAAAH/A/wAAAB/4P+AAAAP+D/wAAAD/g/+AAAAf4H/wAAAD+B/+AAAAfwf/wAAAD+D/+AAAAfw//wAAAD+P/+AAAAf///wAAAD//7+AAAAP/+fwAAAB//z+AAAAH/8fwAAAAf/D+AAAAB/wfwAAAAD4B8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgAAACAAB/AAAB8AAP8AAAfwAB/wAAD+AAP+AAAfwcB/4AAD+HwH/AAAfx/Af8AAD+f4B/gAAf3/AH8AAD//4A/gAAf//AH8AAD//4A/gAAf//gP8AAD//+D/gAAf//9/4AAD/////AAAf8f//wAAD/B//+AAAfwP//gAAB8Af/4AAAHAB/8AAAAAAB8AAAAAAAAAAAAAAAAQAAAAAAAfgAAAAAA/+AAAAAA//wAAAAB//+AAAAB///wAAAB///+AAAAf///wAAAD///+AAAA//8fwAAAD/8D+AAAAf8AfwAAAB8AD+AAAAAAB//4AAAAAf//gAAAAD//8AAAAA///gAAAAD//8AAAAAf//AAAAAA//wAAAAAD+AAAAAAAPgAAAAAAA4AAAAAAAAAAAAA//gBAAAAP/+A+AAAD//4P8AAAf//B/gAAD//4P+AAAf//B/4AAD//4H/AAAfx/Af8AAD+P4B/gAAfx/AP8AAD+P4A/gAAfx/AH8AAD+P4A/gAAfx/gP8AAD+P+D/gAAfw///4AAD+H///AAAfwf//wAAD+B//8AAAPgP//gAAAAAf/wAAAAAB/8AAAAAAB8AAAAAAAAAAAAAAAAAAAAAAD+AAAAAAD/8AAAAAB//4AAAAAf//gAAAAP//+AAAAH///4AAAD////gAAA//wf8AAAf/8B/wAAP//AH+AAB//wAfwAAf/+AD+AAD//wAfwAAP/+AD+AAB+fwAfwAADD/AH+AAAAf8B/gAAAB/wf8AAAAP///gAAAA///4AAAAD//+AAAAAP//gAAAAA//4AAAAAD/+AAAAAAD+AAAAAAAAAAAAAAAAAAAAAAA4AAAAAAAPgAAAAAAD+AAAAAAAfwAAD4AAD+AAB/gAAfwAA/8AAD+AAP/gAAfwAH/8AAD+AD//gAAfwB//4AAD+A//8AAAfwf/+AAAD+P//AAAAfz//gAAAD///4AAAAf//8AAAAD//+AAAAAf//AAAAAD//gAAAAAf/wAAAAAD/8AAAAAAf+AAAAAAD/AAAAAAAPgAAAAAAAAAAAAAAAAAAAAAAAAAP4AAAAAAH/wAAAAAD//gAAAB8//+AAAA////4AAAf////AAAD////8AAA///j/gAAP//4P+AAB//+A/wAAP4/gD+AAB+D8AfwAAPwfgD+AAB/H+A/wAAP//wH+AAA///B/wAAH////8AAAf////gAAA////4AAAD8//+AAAAAD//gAAAAAP/4AAAAAAf8AAAAAAAIAAAAAAAAAAAAAAAH+AAAAAAD/+AAAAAB//4AAAAAf//gAAAAH//+AAAAA///4AAAAP///AAAAB/wf8AAAAf4B/gAAAD/AH+GAAAfwA/z4AAD+AD//gAAfwAf/8AAD+AD//gAAfwA//8AAD/AH//AAAf8B//wAAB/w//4AAAP///8AAAA///+AAAAD///gAAAAP//wAAAAA//4AAAAAD/8AAAAAAD+AAAAAAAAAAAAAAAAAAAAAAA4AA4AAAAPgAPgAAAD+AD+AAAAfwAfwAAAD+AD+AAAAfwAfwAAAB8AB8AAAACAACAAAAAAAAAA="), 46, atob("CRAbDhkZFxkbGhkbCg=="), 51+(scale<<8)+(1<<16));
};

g.clear();
g.setColor('#fff');
g.fillRect(0,0,g.getWidth(), g.getHeight());

g.setFontArista2(2);
g.setFontAlign(0,-1);

g.setColor('#000');
g.drawString("09", g.getWidth()/2, 0);

//g.setColor('#fb8');
g.drawString("30", g.getWidth()/2, g.getHeight()/2);
