
Graphics.prototype.setFontSFSquareHead = function(scale) {
  // Actual height 26 (29 - 4)
  g.setFontCustom(atob("AAAAPAAAAADwAAAAA8AAAAAPAAAAAAAAAAAAAAAAAAOAAAAAfwAAAB/8AAAH//AAAP//AAA//8AAD//4AAA//gAAAP+AAAAD8AAAAAQAAAAAAAAAAAD////AA////wAP///8AD////AA8AADwAPAAA8ADwAAPAA8AADwAPAAA8ADwAAPAA8AADwAPAAA8ADwAAPAA8AADwAPAAA8ADwAAPAA8AADwAPAAA8ADwAAPAA8AADwAPAAA8ADwAAPAA8AADwAP///8AD////AA////wAP///8AAAAAAAAAAAAAAPAAA8ADwAAPAA8AADwAPAAA8ADwAAPAA8AADwAPAAA8ADwAAPAA8AADwAPAAA8ADwAAPAA////wAP///8AD////AA////wAAAAA8AAAAAPAAAAADwAAAAA8AAAAAPAAAAADwAAAAA8AAAAAPAAAAADwAAAAA8AAAAAPAAAAADwAAAAAAAAAAAAAA8B//wAPAf/8ADwH//AA8B//wAPAeA8ADwHgPAA8B4DwAPAeA8ADwHgPAA8B4DwAPAeA8ADwHgPAA8B4DwAPAeA8ADwHgPAA8B4DwAPAeA8ADwHgPAA8B4DwAPAeA8ADwHgPAA8B4DwAPAeA8AD//gPAA//4DwAP/+A8AD//gPAAAAAAAAAAAAAADwHgPAA8B4DwAPAeA8ADwHgPAA8B4DwAPAeA8ADwHgPAA8B4DwAPAeA8ADwHgPAA8B4DwAPAeA8ADwHgPAA8B4DwAPAeA8ADwHgPAA8B4DwAPAeA8ADwHgPAA8B4DwAPAeA8ADwHgPAA8B4DwAP///8AD////AA////wAP///8AAAAAAAAAAAAAAP/+AAAD//gAAA//4AAAP/+AAAAAHgAAAAB4AAAAAeAAAAAHgAAAAB4AAAAAeAAAAAHgAAAAB4AAAAAeAAAAAHgAAAAB4AAAAAeAAAAAHgAAAAB4AAAAAeAAAAAHgAAAAB4AAAAAeAAAAAHgAAA////wAP///8AD////AA////wAAAAAAAAAAAAAA//4DwAP/+A8AD//gPAA//4DwAPAeA8ADwHgPAA8B4DwAPAeA8ADwHgPAA8B4DwAPAeA8ADwHgPAA8B4DwAPAeA8ADwHgPAA8B4DwAPAeA8ADwHgPAA8B4DwAPAeA8ADwHgPAA8B4DwAPAeA8ADwH//AA8B//wAPAf/8ADwH//AAAAAAAAAAAAAAD////AA////wAP///8AD////AA8B4DwAPAeA8ADwHgPAA8B4DwAPAeA8ADwHgPAA8B4DwAPAeA8ADwHgPAA8B4DwAPAeA8ADwHgPAA8B4DwAPAeA8ADwHgPAA8B4DwAPAeA8ADwHgPAA8B4DwAPAf/8ADwH//AA8B//wAPAf/8AAAAAAAAAAAAAAPAAAAADwAAAAA8AAAAAPAAAAADwAAAAA8AAAAAPAAAAADwAAAAA8AAAAAPAAAAADwAAAAA8AAAAAPAAAAADwAAAAA8AAAAAPAAAAADwAAAAA8AAAAAPAAAAADwAAAAA8AAAAAPAAAAADwAAAAA////wAP///8AD////AA////wAAAAAAAAAAAAAA////wAP///8AD////AA////wAPAeA8ADwHgPAA8B4DwAPAeA8ADwHgPAA8B4DwAPAeA8ADwHgPAA8B4DwAPAeA8ADwHgPAA8B4DwAPAeA8ADwHgPAA8B4DwAPAeA8ADwHgPAA8B4DwAPAeA8AD////AA////wAP///8AD////AAAAAAAAAAAAAAD//gPAA//4DwAP/+A8AD//gPAA8B4DwAPAeA8ADwHgPAA8B4DwAPAeA8ADwHgPAA8B4DwAPAeA8ADwHgPAA8B4DwAPAeA8ADwHgPAA8B4DwAPAeA8ADwHgPAA8B4DwAPAeA8ADwHgPAA8B4DwAP///8AD////AA////wAP///8AAAAAAAAAAAAAAAAeA8AAAHgPAAAB4DwAAAeA8AAAAAAAAAAAAA"), 46, atob("BgwdHR0dHR0dHR0dBg=="), 38+(scale<<8)+(1<<16));
};


g.clear();
g.setColor('#000');
g.fillRect(0,0,g.getWidth(), g.getHeight());

g.setFontSFSquareHead(3);
g.setFontAlign(0,0);
g.setColor('#fff');
g.drawString("09", g.getWidth()/2, g.getHeight()/4);

g.drawString("30", g.getWidth()/2, 3*g.getHeight()/4);
